// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPackage(arg1:main.PackageInput):Promise<main.QuoteState>;

export function AnalyzeAddress(arg1:string):Promise<main.AddressResult>;

export function CalculateQuote():Promise<main.QuoteState>;

export function ClearPackages():Promise<main.QuoteState>;

export function DeletePackage(arg1:number):Promise<main.QuoteState>;

export function GetInitialState():Promise<main.QuoteState>;

export function GetProvinces():Promise<string[]>;

export function SetDestination(arg1:string,arg2:string):Promise<main.QuoteState>;
