// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPackage(arg1) {
  return window['go']['main']['App']['AddPackage'](arg1);
}

export function AnalyzeAddress(arg1) {
  return window['go']['main']['App']['AnalyzeAddress'](arg1);
}

export function CalculateQuote() {
  return window['go']['main']['App']['CalculateQuote']();
}

export function ClearPackages() {
  return window['go']['main']['App']['ClearPackages']();
}

export function DeletePackage(arg1) {
  return window['go']['main']['App']['DeletePackage'](arg1);
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function GetProvinces() {
  return window['go']['main']['App']['GetProvinces']();
}

export function SetDestination(arg1, arg2) {
  return window['go']['main']['App']['SetDestination'](arg1, arg2);
}
